services:
  docs:
    image: salon_jelena_local_docs
    container_name: salon_jelena_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./salon_jelena:/app/salon_jelena:z
    ports:
      - '9000:9000'
    command: /start-docs
