# Generated by Django 5.0.11 on 2025-01-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obavijest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=100)),
                ('pod_naslov', models.CharField(max_length=150)),
                ('tekst', models.CharField(blank=True)),
                ('url', models.CharField(blank=True, max_length=512, null=True)),
                ('slika',models.IntegerField(blank=True)),
            ],
            options={
                'verbose_name': 'Obavijesti',
            },
        ),
    ]
