# Generated by Django 5.0.11 on 2025-01-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jelena', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='obavijest',
            options={'verbose_name_plural': 'Obavijesti'},
        ),
        migrations.AlterField(
            model_name='obavijest',
            name='pod_naslov',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='obavijest',
            name='slika',
            field=models.ImageField(blank=True, upload_to='obavijest_slike'),
        ),
    ]
