# Generated by Django 5.0.11 on 2025-02-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jelena', '0002_djecje_frizure_muske_frizure_produkti_zenske_frizure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djecje_frizure',
            name='cijena',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='djecje_frizure',
            name='ime',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='muske_frizure',
            name='cijena',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='muske_frizure',
            name='ime',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='produkti',
            name='cijena',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='produkti',
            name='ime',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='zenske_frizure',
            name='cijena',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='zenske_frizure',
            name='ime',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
