# Generated by Django 5.0.11 on 2025-01-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jelena', '0002_alter_obavijest_options_alter_obavijest_pod_naslov_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zenske_slike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
                ('cijena', models.IntegerField()),
                ('opis', models.CharField(blank=True, max_length=100)),
                ('slika', models.ImageField(upload_to='frizure')),
            ],
        ),
    ]
