# Generated by Django 5.0.11 on 2025-01-27 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jelena', '0005_alter_zenske_slike_slika'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Zenske_slike',
            new_name='Zenske_frizure',
        ),
        migrations.AlterModelOptions(
            name='zenske_frizure',
            options={'verbose_name_plural': 'Zenske Frizure'},
        ),
    ]
