# Generated by Django 5.0.11 on 2025-02-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jelena', '0006_alter_djecje_frizure_ime_alter_muske_frizure_ime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djecje_frizure',
            name='ime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='muske_frizure',
            name='ime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='produkti',
            name='ime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zenske_frizure',
            name='ime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
