# Generated by Django 5.0.11 on 2025-01-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jelena', '0006_rename_zenske_slike_zenske_frizure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frizure',
            name='opis',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
