# Generated by Django 5.0.11 on 2025-01-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jelena', '0007_alter_zenske_frizure_opis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Djecje_frizure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
                ('cijena', models.IntegerField()),
                ('opis', models.CharField(blank=True)),
                ('slika', models.ImageField(blank=True, null=True, upload_to='zenske_frizure')),
                ('video', models.FileField(blank=True, null=True, upload_to='zenske_frizure/frizure_video')),
            ],
            options={
                'verbose_name_plural': 'Djecje Frizure',
            },
        ),
        migrations.CreateModel(
            name='Muske_frizure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
                ('cijena', models.IntegerField()),
                ('opis', models.CharField(blank=True)),
                ('slika', models.ImageField(blank=True, null=True, upload_to='zenske_frizure')),
                ('video', models.FileField(blank=True, null=True, upload_to='zenske_frizure/frizure_video')),
            ],
            options={
                'verbose_name_plural': 'Muske Frizure',
            },
        ),
        migrations.CreateModel(
            name='Produkti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
                ('cijena', models.IntegerField()),
                ('opis', models.CharField(blank=True)),
                ('slika', models.ImageField(blank=True, null=True, upload_to='zenske_frizure')),
                ('video', models.FileField(blank=True, null=True, upload_to='zenske_frizure/frizure_video')),
            ],
            options={
                'verbose_name_plural': 'Produkti',
            },
        ),
        migrations.AlterField(
            model_name='zenske_frizure',
            name='opis',
            field=models.CharField(blank=True),
        ),
    ]
