# Generated by Django 5.0.11 on 2025-02-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jelena', '0007_alter_djecje_frizure_ime_alter_muske_frizure_ime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='djecje_frizure',
            name='datum_uploada',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='muske_frizure',
            name='datum_uploada',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='produkti',
            name='datum_uploada',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='zenske_frizure',
            name='datum_uploada',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
