# Generated by Django 5.0.11 on 2025-02-04 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jelena', '0008_djecje_frizure_datum_uploada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muske_frizure',
            name='pocetna_stranica',
        ),
    ]
