# Generated by Django 5.0.11 on 2025-01-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jelena', '0008_djecje_frizure_muske_frizure_produkti_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='djecje_frizure',
            name='pocetna_stranica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='muske_frizure',
            name='pocetna_stranica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produkti',
            name='pocetna_stranica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='frizure',
            name='pocetna_stranica',
            field=models.BooleanField(default=False),
        ),
    ]
