# Generated by Django 5.0.11 on 2025-01-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jelena', '0009_djecje_frizure_pocetna_stranica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djecje_frizure',
            name='slika',
            field=models.ImageField(blank=True, null=True, upload_to='frizure'),
        ),
        migrations.AlterField(
            model_name='djecje_frizure',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='frizure_video'),
        ),
        migrations.AlterField(
            model_name='muske_frizure',
            name='slika',
            field=models.ImageField(blank=True, null=True, upload_to='frizure'),
        ),
        migrations.AlterField(
            model_name='muske_frizure',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='frizure_video'),
        ),
        migrations.AlterField(
            model_name='produkti',
            name='slika',
            field=models.ImageField(blank=True, null=True, upload_to='frizure'),
        ),
        migrations.AlterField(
            model_name='produkti',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='frizure_video'),
        ),
        migrations.AlterField(
            model_name='zenske_frizure',
            name='slika',
            field=models.ImageField(blank=True, null=True, upload_to='frizure'),
        ),
        migrations.AlterField(
            model_name='zenske_frizure',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='frizure_video'),
        ),
    ]
